### ISSUE TITLE
REU check mistakes

### ISSUE THREAD

**Issue by jpcompton** [christopherkobayashi/infocom64#1] opened 2020-09-18 16:35 UTC
1. With no REU, infocom 3/4/5 reports 16384k REU found. (Confirmed on real hardware as well as VICE 3.4.) This also overrides emulated GeoRAM - interpreter only reports seeing the (nonexistent) 16 MB REU and tries to use that, crashing.

2. On real hardware, 2 MB REU (CMD 1750XL) is reported as 16MB. (but story.dat seems to be more-or-less correctly loaded in and is playable.) A VICE 2 MB REU is reported correctly as 2 MB.

**Comment by christopherkobayashi** [comment] 2020-12-29 07:52
Very sorry about this taking so long.

The problem was in the way I was detecting the number of REU banks -- I was transferring a page full of $BB to the REU, then back to the same location in memory, without first setting the test buffer to anything except $BB.  I was also not correctly signalling that an REU was not found, which was bollixing up GeoRAM detection.

Thanks for letting me know.  Fixed.

**Closed** 2020-12-29 07:52 UTC

**Comment by christopherkobayashi** [comment] 2020-12-29 08:51
On my Ultimate64, the REU is also unilaterally detected as 16384k.  As you say, this isn't happening on VICE.

Additionally, the GeoRAM detection routine (which works as intended on VICE) always succeeds on the Ultimate64.  I don't have "real" hardware anymore, so I'm unsure if this is a bug in the Ultimate64 or in VICE.

I've made GeoRAM a compile-time option (disabled by default) for the time being.  Thanks for letting me know, and again I apologize for the very late attention to this ...
